%options.in_files = {'axis_sweep_out.dat'};
%options.issweep = true;
%options.in_files = {'Z_rot_md.dat'};
%options.cal_file = 'XYZ_hr_cal_DLT_corrected.mat';
options.cal_file = 'XYZ_hr_cal_concentric.mat';
%options.cal_file = 'XYZ_hr_cal.mat';
%options.cal_file = 'se_quadrupole_all_hr_cal.mat';
%options.cal_file = 'se_quadrupole_all_hr_cal_skew_corrected.mat';
%options.linear_correction = true;
options.sg_filt_F = 11;
options.onax_ignore_Rz_coupling = false;
%options.do_optimize = 'both';
options.stage_coords = false;
%options.pose_solution = 'UKF';
options.pose_solution = 'kim18';
options.xyz_exaggerate = 1;
options.rot_xyz_exaggerate = 3; % m/rad
